package com.ScheduleMaker.ScheduleMaker.Entities;


import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "daily_plans", uniqueConstraints = @UniqueConstraint(columnNames = {"schedule_id", "plan_date"}))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DailyPlan extends Auditable {

    // Primary key, auto-generated by MySQL.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Which schedule this day's plan belongs to.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "schedule_id", nullable = false)
    private Schedule schedule;

    // The calendar date this plan is for. Unique per schedule (see table constraint)
    // so the scheduler can never accidentally generate two plans for the same day.
    @Column(name = "plan_date", nullable = false)
    private LocalDate date;

    // Hours available on this specific date - normally equals the schedule's
    // dailyAvailableHours, but kept per-row in case you later let users override
    // a single day (e.g. "I have less time today").
    @Column(name = "total_available_hours", nullable = false)
    private Double totalAvailableHours;

    // The individual topic-allocations that make up this day's plan.
    @Builder.Default
    @OneToMany(mappedBy = "dailyPlan", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<DailyTask> tasks = new ArrayList<>();
}
