package com.ScheduleMaker.ScheduleMaker.Entities;


import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Top-level container that lets a single User own multiple independent
 * study plans at once. Deadline and daily time budget live here (not on
 * User) so two schedules can run on completely different timelines.
 */
@Entity
@Table(name = "schedules")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Schedule extends Auditable {

    // Primary key, auto-generated by MySQL.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Owner of this schedule.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // User-facing label, e.g. "Semester Finals" or "GATE Prep".
    @Column(nullable = false, length = 150)
    private String name;

    // First day the schedule is active - used to compute days elapsed / days remaining.
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    // Deadline the whole plan is built around.
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    // Hours per day this schedule is allowed to consume - independent per schedule,
    // since a user may run two schedules in parallel with different daily budgets.
    @Column(name = "daily_available_hours", nullable = false)
    private Double dailyAvailableHours;

    // ACTIVE / COMPLETED / ARCHIVED - controls whether this schedule is included
    // in daily plan generation and rescheduling.
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ScheduleStatus status = ScheduleStatus.ACTIVE;

    // All subjects the user added under this schedule.
    @Builder.Default
    @OneToMany(mappedBy = "schedule", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Subject> subjects = new ArrayList<>();

    // One DailyPlan per calendar date this schedule has generated tasks for.
    @Builder.Default
    @OneToMany(mappedBy = "schedule", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<DailyPlan> dailyPlans = new ArrayList<>();
}
