package com.ScheduleMaker.ScheduleMaker.Entities;


import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "subjects")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Subject extends Auditable {

    // Primary key, auto-generated by MySQL.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Which schedule this subject belongs to.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "schedule_id", nullable = false)
    private Schedule schedule;

    // Display name, e.g. "Organic Chemistry".
    @Column(nullable = false, length = 150)
    private String name;

    // 1 (never seen it) - 5 (know it well). Asked once when the subject is
    // created, then used to shrink every topic's min_hours via a
    // familiarity_factor before the scheduler's slack-pool math runs.
    // Deliberately subject-level, not per-topic, to keep onboarding to one question.
    @Column(name = "self_rated_familiarity", nullable = false)
    private Integer selfRatedFamiliarity;

    // The parsed topic list from this subject's uploaded syllabus.
    @Builder.Default
    @OneToMany(mappedBy = "subject", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Topic> topics = new ArrayList<>();
}
