package com.ScheduleMaker.ScheduleMaker.Entities;

/**
 * A historical record of what happened on a specific scheduled day.
 * FAILED here just means that day's allocated hours weren't logged -
 * it does NOT terminate the Topic; the topic simply stays PENDING/IN_PROGRESS
 * and re-enters tomorrow's candidate pool with its days_pending incremented.
 */
public enum TaskStatus {
    SCHEDULED,  // default state - generated by the scheduler, not yet acted on by the user
    COMPLETED,  // user logged the full allocated_hours against the topic
    PARTIAL,    // user logged some but not all of the allocated_hours
    FAILED      // user logged zero progress on this task for the day
}
