package com.ScheduleMaker.ScheduleMaker.Entities;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "topics")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Topic extends Auditable {

    // Primary key, auto-generated by MySQL. NOT used for ordering - see orderIndex.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Which subject this topic belongs to.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;

    // Explicit sequence position set from syllabus parse order (or manual reorder).
    // Deliberately separate from the DB id, which just reflects insertion order
    // and would break "next topic" queries the moment a topic is re-parsed or added later.
    @Column(name = "order_index", nullable = false)
    private Integer orderIndex;

    // Topic title as extracted from the syllabus, e.g. "Newman Projections".
    @Column(nullable = false, length = 200)
    private String name;

    // Minimum hours the LLM estimated this topic needs, already multiplied by
    // the subject's familiarity_factor. This is the "done" threshold used by
    // getStatus() and the value the scheduler tries to fit into daily_available_hours.
    @Column(name = "min_hours", nullable = false)
    private Double minHours;

    // Upper bound on hours - min_hours plus this topic's share of the schedule's
    // slack pool, proportional to base_priority. Represents optional extra depth time.
    @Column(name = "max_hours", nullable = false)
    private Double maxHours;

    // Running total of hours actually logged against this topic across all
    // DailyTasks. Drives getStatus() - never set status directly.
    @Builder.Default
    @Column(name = "hours_completed", nullable = false)
    private Double hoursCompleted = 0.0;

    // Stable importance (1-5) from the LLM/syllabus weighting. Represents how
    // exam-critical the topic is - independent of how long it's been waiting.
    @Column(name = "base_priority", nullable = false)
    private Integer basePriority;

    // Number of consecutive days this topic has remained not-DONE. Incremented
    // by a daily scheduled job and fed into getEffectivePriority() so a
    // low-priority topic can't get starved forever (aging/anti-starvation).
    @Builder.Default
    @Column(name = "days_pending", nullable = false)
    private Integer daysPending = 0;

    // Every day this topic was scheduled on, across possibly many DailyPlans,
    // since a topic can be split across multiple daily slots.
    @Builder.Default
    @OneToMany(mappedBy = "topic", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<DailyTask> dailyTasks = new ArrayList<>();

    // Derived, not stored - see TopicStatus for what each value means.
    @Transient
    public TopicStatus getStatus() {
        if (hoursCompleted >= minHours) return TopicStatus.DONE;
        if (hoursCompleted > 0) return TopicStatus.IN_PROGRESS;
        return TopicStatus.PENDING;
    }

    // How many hours still need to be scheduled for this topic to reach minHours.
    @Transient
    public double getRemainingHours() {
        return Math.max(0, minHours - hoursCompleted);
    }

    // basePriority boosted by how long the topic has been waiting - what the
    // daily selector actually sorts on, instead of raw basePriority.
    @Transient
    public double getEffectivePriority(double agingFactor) {
        return basePriority + (daysPending * agingFactor);
    }
}
